import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ProgressBar from '../components/ProgressBar';
import Form from '../components/Form';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <img className={styles.logo} src='./logo.png' />
        <div className={styles.container}>
          <div className={styles.topInfo}>
            <h1>Заявка на кредитную карту</h1>
            <h3>Кредитная карта с целым годом без %</h3>
            <div className={styles.box}>
              <div>
                <img src='./card.png' alt='card' />
              </div>
              <div className={styles.featureBox}>
                <ul>
                  <li className={styles.feature}>
                    <div>
                      <div className={styles.featureTitle}>Год без %</div>
                      <div className={styles.featureText}>на покупки в первые 30 дней</div>
                    </div>
                  </li>
                  <li className={styles.feature}>
                    <div>
                      <div className={styles.featureTitle}>0 ₽ обслуживание</div>
                      <div className={styles.featureText}>навсегда и без условий</div>
                    </div>
                  </li>
                  <li className={styles.feature}>
                    <div>
                      <div className={styles.featureTitle}>до 50 000 ₽</div>
                      <div className={styles.featureText}>снимайте без комиссии каждый месяц</div>
                    </div>
                  </li>
                  <li className={styles.feature}>
                    <div>
                      <div className={styles.featureTitle}>500 000 ₽</div>
                      <div className={styles.featureText}>максимальный кредитный лимит</div>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <ProgressBar />
          <Form />
        </div>
        <div className={styles.footer}>
          <div className={styles.footerContainer}>
            <div className={styles.footerLink}>
              <a>
                <img src='./pdf.png' alt='pdf' />
                <span>Памятка о беспроцентном периоде по кредитной карте</span>
              </a>
            </div>
            <div className={styles.footerLink}>
              <a>
                <img src='./pdf.png' alt='pdf' />
                <span>Кредитная карта 1 год без % Тарифы</span>
              </a>
            </div>
            <div className={styles.footerLink}>
              <a>
                <img src='./pdf.png' alt='pdf' />
                <span>Правила акции</span>
              </a>
            </div>
            <div className={styles.footerText}>
              Длительность БП по данным исследования banki.ru. Беспроцентный период (БП) 365 дней начинается со дня после 1-й покупки и распространяется на покупки, совершённые в периоде = 30 дням после заключения ДС о БП (далее — Период). После окончания Периода, при совершении покупки на 31 день и далее, БП = 100 дням со дня после покупки. БП действует при ежемесячном платеже не менее 3-10% долга (не 300 ₽) и погашении всей задолженности за срок БП. Иначе % начисляются с 1-го дня БП до полного погашения задолженности. % ставка: 11,99%—69,99% годовых, снятие до 50 000 ₽ в месяц без комиссии, лимит кредитования: 5000—500 000 ₽ (индивидуально). Беспроцентный период на операции снятия наличных и приравненные к ним не распространяется. Погашение задолженности по покупкам, совершённым после окончания Периода, возможно только после полного погашения задолженности по покупкам за Период. Кэшбэк 1000 ₽. за первую покупку от 1000 ₽. Акция с 14.11.22 по 31.12.22. Не оферта. Подробнее:alfabank.ru. АО «Альфа-Банк». Ген. лицензия ЦБ РФ № 1326 от 16.01.2015 г.
            </div>
            <div className={styles.footerText}>
              Генеральная лицензия Банка России №1326 от 16 января 2015 г. «Альфа-Банк» является частью консорциума «Альфа-Групп» © 2001–2023 «Альфа-Банк» 107078, Москва, ул. Каланчевская, 27. У вас есть вопросы по заполнению анкеты? Звоните: 8 800 200 2551  или
              <a><span>напишите нам</span></a>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
